# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_and_export do
    increment_version_number(version_number: "1.1")
    increment_build_number(
      build_number: 1.1
    )
    gym(
      export_options: {
        provisioningProfiles: {
          "ua.edu.ukma.apple-env.matvieieva.CatsAndModules-YevaPilat2" => "4a02c8d2-bd86-434b-a85b-e0bfb3852e00"
        }
      }
    )
    firebase_app_distribution(
      app: "1:701551039095:ios:dc6c39e49394f8f09cac72",
      testers: "o.frankiv@ukma.edu.ua",
      release_notes: "Перевірка bitrise"
    )
  end

  lane :take_screenshots do
    capture_screenshots
  end
end

